version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Release
platform: Any CPU
init:
- cmd: git lfs uninstall
before_build:
- ps: >-
    nuget restore src\RiaServices.sln
build:
  project: src\RiaServices.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: 'NuGet\bin\*.nupkg'
before_test:
- ps: >-
    .\Setup-TestDatabases.ps1 -UseSqlCmd
test: off 
